import Head from 'next/head'
import { useEffect, useState } from 'react'

function sortData(data, key, s) {
  const unsorted = [...data]
  function compareScores(a, b) {
    if (a.scores[key] > b.scores[key]) return -1*s;
    if (a.scores[key] < b.scores[key]) return s;
    return 0;
  }
  function compareKeys(a, b) {
    if (a[key] > b[key]) return -1*s;
    if (a[key] < b[key]) return s;
    return 0;
  }
  if(Object.keys(unsorted[0].scores).includes(key)) return unsorted.sort(compareScores)
  return unsorted.sort(compareKeys)
}

function Row({rdata, i}) {
  const { id, player_name, team } = rdata
  const { fpl, md, xG, odds, variance } = rdata.scores
  return (
    <tr className="border-dotted border-2 border-sky-500 ...">
      <td>{i}</td>
      <td>{id}</td>
      <td>{player_name}</td>
      <td>{team}</td>
      <td>{fpl}</td>
      <td>{md}</td>
      <td>{odds}</td>
      <td>{xG}</td>
      <td>{variance}</td>
    </tr>
  )
}

function Table({ mdata, setSortOpts }) {
  
  const mappedKeys = { nr: 'Nr.',
                    id: 'ID',
                    player_name: 'Manager',
                    team: 'Team',
                    fpl: 'FPL',
                    md: 'MD',
                    odds: 'Odds',
                    xG: 'xG',
                    variance: 'Variance'
                  }

  function handleClick(e) {
    setSortOpts((opts) => { return {...opts, key: e.target.id, order: opts.order*-1 } } )
  }

  return (
    <table className="table-fixed border-separate border-spacing-0 border border-slate-500 ...">
      <thead>
        <tr>
          {Object.keys(mappedKeys).map((k,i,arr)=>{ return <th key={k} id={k} onClick={handleClick}>{mappedKeys[k]}</th>})}
        </tr>
      </thead>
      <tbody>
        {mdata.map((entry, i) => {
            return (
              <Row key={entry.id} rdata={entry} i={i+1}/>
            )
        })}
      </tbody>
    </table>
  )
}

export default function Home() {
  const [data, setData] = useState([])
  const [sortOpts, setSortOpts] = useState( { key: 'md', order: 1 } )

  useEffect(() => {
    fetch('/api/scores')
      .then((response) => {
        if (!response.ok) {
          throw new Error(`HTTP error! Status: ${response.status}`);
        }
    
        return response.json();
      })
      .then((json) => {
        setData(json);
      })
  },[])

  useEffect(() => {
    let sorted
    if(data.length > 0) {
      sorted = sortData(data, sortOpts.key, sortOpts.order);
      setData(sorted);
  }
  },[sortOpts.order, sortOpts.key])

  return (
    <div>
      <Head>
        <title>Analytics and friends</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto px-4">
        <h1 className="text-4xl my-6 font-blue-200 ...">
        Analytics Elite 64 (D1, D2) + #Elite64 + #elite64NOR
        </h1>
        <Table mdata={data} setSortOpts={setSortOpts}/>
      </main>
      <footer>
        <p></p>
      </footer>
    </div>
  )
}
