import Head from 'next/head'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Analytics and friends</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-blue-200">
          Elite leagues
        </h1>
        <h2 className="text-2xl font-red-200">
          ...
        </h2>
      </main>
      <footer>
        <p></p>
      </footer>
    </div>
  )
}
